version: "3.9"

services:
  profile_db:
    image: mysql:8.0
    container_name: profile-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: profile_db
      MYSQL_USER: profile_user
      MYSQL_PASSWORD: profile_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
